baseURL = 'http://confluent-kr.github.io/'
languageCode = 'ko-KR'
title = 'Confluent KR Community'
theme = "cleanwhite"

preserveTaxonomyNames = true
paginate = 10 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML"]


[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "컨플루언트 | confluent | confluent-kr"
  description = "컨플루언트, 데이터 스트리밍, 카프카, Kafka, Flink"
  keyword = "컨플루언트, Kafka, ksqldb, connect, flink, data streaming, stream processing, data in motion, confluent"
  slogan = "Data in Motion"

  image_404 = "img/404-bg.jpg"
  title_404 = " :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  # sidebar_avatar = "img/zhaohuabing.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  # disqus_proxy = ""
  # disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  # twikoo_env_id = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  # friends = true
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "confluent-korea@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/confluentinc"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/confluentinc"
  #wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.bookmark_link]]
    title =  "Martin Fowler"
    href =  "https://martinfowler.com"
  [[params.bookmark_link]]
    title = "ServiceMesher"
    href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
    title =  "Pxhere"
    href = "https://pxhere.com"
  [[params.bookmark_link]]
    title = "unsplash"
    href = "https://unsplash.com"
  
  [[params.addtional_menus]]
    title =  "ARCHIVE"
    href =  "/archive/"
  [[params.addtional_menus]]
    title =  "NOTES"
    href =  "/notes/"
  [[params.addtional_menus]]
    title =  "ABOUT"
    href =  "/about/"

[params.giscus]
data_repo="confluent-kr/confluent-kr.github.io"
data-repo-id="R_kgDOJ5w68Q"
data-category="Q&A"
data-category-id="DIC_kwDOJ5w68c4CXytb"
data-mapping="pathname"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-input-position="bottom"
data-theme="preferred_color_scheme"
data-lang="ko"
crossorigin="anonymous"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"